import type { Metadata } from 'next';
import {
    Cormorant_Garamond,
    Playfair_Display,
    Montserrat,
    Lato,
} from 'next/font/google';
import './globals.css';
import Header from '@/components/layout/header';

const playfair = Playfair_Display({
    variable: '--font-playfair',
    subsets: ['latin'],
    style: ['normal', 'italic'],
    weight: ['400', '500'],
});

const cormorant = Cormorant_Garamond({
    variable: '--font-cormorant',
    subsets: ['latin'],
    style: ['normal', 'italic'],
    weight: ['400', '500'],
});

const montserrat = Montserrat({
    variable: '--font-montserrat',
    subsets: ['latin'],
    weight: ['300', '400', '500', '600'],
});

const lato = Lato({
    variable: '--font-lato',
    subsets: ['latin'],
    weight: ['300', '400', '700'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es">
            <body>
                <Header />
                {children}
            </body>
        </html>
    );
}
